kind: pipeline
type: docker
name: build db-concat

steps:
- name: build and push
  image: plugins/docker
  settings:
    repo: johnktaylor/db-concat
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest